image: electronuserland/builder:wine

stages:
  - build

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/
    - node_modules/

build_job:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run transpile:electron
    - npm run build
    - npx electron-builder --linux --win

  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - dist/*.exe
      - dist/*.AppImage
      - dist/*.deb
      - dist/latest.yml
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG
